#ifndef GAME_ATTACKS_H
#define GAME_ATTACKS_H

using namespace std;

class attacks {
public:
    string attackOneDescriptionChooseYourCharacter;
    string attackTwoDescriptionChooseYourCharacter;
    string attackThreeDescriptionChooseYourCharacter;
    int amountOfAttacks;



    attacks(string a, string b, string c, int d) {
        attackOneDescriptionChooseYourCharacter = a;
        attackTwoDescriptionChooseYourCharacter = b;
        attackThreeDescriptionChooseYourCharacter = c;
        amountOfAttacks = d;
    }
};

attacks infernoAttacks("                                                            \n"
                       "                        Attack one                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "         Shield Melt                                        \n"
                       "         ===========                                        \n"
                       "                                                            \n"
                       "        Cost: 40 battery                                    \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        Effect:                                             \n"
                       "            Destroy shield of the enemy, if the enemy       \n"
                       "            doesn't have shield active deal 2 damage        \n"
                       "            to their armour. Than deal normal damage        \n"
                       "            to enemy.                                       \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                        Attack two                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "         Flamethrower Overclock                             \n"
                       "         ======================                             \n"
                       "                                                            \n"
                       "        Cost: 20 battery, 20 data                           \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        Effect:                                             \n"
                       "          Deal a lot of damage to your enemy. Than          \n"
                       "          give them burning effect.                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                       Attack three                         \n"
                       "                       ============                         \n"
                       "                                                            \n"
                       "         Smoke Grenade                                      \n"
                       "         =============                                      \n"
                       "                                                            \n"
                       "        Cost: 30 battery, 15 data                           \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        Effect:                                             \n"
                       "         Give your enemy two effects, burning and poison    \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ", 3);

attacks atlasAttacks ("                                                            \n"
                      "                        Attack one                          \n"
                      "                        ==========                          \n"
                      "                                                            \n"
                      "         Data leach                                         \n"
                      "         ==========                                         \n"
                      "                                                            \n"
                      "        Cost: 40 battery                                    \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        Effect:                                             \n"
                      "           Lower the current stat of data of your enemy     \n"
                      "           by 25% and add this amount to your data stat.    \n"
                      "           After this deal lower damage to your enemy.      \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                        Attack two                          \n"
                      "                        ==========                          \n"
                      "                                                            \n"
                      "          Data Leak                                         \n"
                      "          =========                                         \n"
                      "                                                            \n"
                      "        Cost: 100% data                                     \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        Effect:                                             \n"
                      "           For every 10 data spent when this activated      \n"
                      "           deal one damage yo your enemy.                   \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                       Attack three                         \n"
                      "                       ============                         \n"
                      "                                                            \n"
                      "         SQL injection                                      \n"
                      "         =============                                      \n"
                      "                                                            \n"
                      "        Cost: 40 data, 15 battery                           \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        Effect:                                             \n"
                      "           Deal normal amount of damage (your atk stat)     \n"
                      "           to your enemy. Than lower the data stat of       \n"
                      "           your enemy by 20.                                \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ", 3);
attacks staticTheIAttacks("                                                            \n"
                   "                        Attack one                          \n"
                   "                        ==========                          \n"
                   "                                                            \n"
                   "      Rewire implants                                       \n"
                   "      ===============                                       \n"
                   "                                                            \n"
                   "        Cost: 40 battery, 15 data                           \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "        Effect:                                             \n"
                   "           Deal low damage to your enemy, that enemy        \n"
                   "           will skip their next turn (you have one          \n"
                   "           more action).                                    \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            ",
                   "                                                            \n"
                   "                        Attack two                          \n"
                   "                        ==========                          \n"
                   "                                                            \n"
                   "      Volume ++                                             \n"
                   "      =========                                             \n"
                   "                                                            \n"
                   "        Cost: 40 battery                                    \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "        Effect:                                             \n"
                   "           Deal high damage to your enemy.                  \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            ",
                   "                                                            \n"
                   "                       Attack three                         \n"
                   "                       ============                         \n"
                   "                                                            \n"
                   "      110% overclock                                        \n"
                   "      ==============                                        \n"
                   "                                                            \n"
                   "        Cost: 40 data, 15 battery                           \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "        Effect:                                             \n"
                   "           Deal normal damage to yourself and than          \n"
                   "           two times this damage to your enemy.             \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            \n"
                   "                                                            ",3);

attacks staticTheIIAttacks ("                                                            \n"
                            "                        Attack one                          \n"
                            "                        ==========                          \n"
                            "                                                            \n"
                            "      Error 404                                             \n"
                            "      =========                                             \n"
                            "                                                            \n"
                            "        Cost: 40 data                                       \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "        Effect:                                             \n"
                            "           Lower data stat of your enemy by 20,             \n"
                            "           then deal normal damage to your enemy.           \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            ",
                            "                                                            \n"
                            "                        Attack two                          \n"
                            "                        ==========                          \n"
                            "                                                            \n"
                            "      Blue screen                                           \n"
                            "      ===========                                           \n"
                            "                                                            \n"
                            "        Cost: 40 battery                                    \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "        Effect:                                             \n"
                            "           Deal high damage to your enemy.                  \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            ",
                            "                                                            \n"
                            "                       Attack three                         \n"
                            "                       ============                         \n"
                            "                                                            \n"
                            "      White screen                                          \n"
                            "      ============                                          \n"
                            "                                                            \n"
                            "        Cost: 15 battery, 15 data                           \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "        Effect:                                             \n"
                            "           Ignore armour and deal normal damage             \n"
                            "           to your enemy (lower their hp and                \n"
                            "           not arm).                                        \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            \n"
                            "                                                            ",3);

attacks hanibalAttacks ("                                                            \n"
                        "                        Attack one                          \n"
                        "                        ==========                          \n"
                        "                                                            \n"
                        "      Big bite                                              \n"
                        "      ========                                              \n"
                        "                                                            \n"
                        "        Cost: 15 battery                                    \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "        Effect:                                             \n"
                        "           Ignore armour and deal normal damage             \n"
                        "           to your enemy (lower their hp and                \n"
                        "           not arm).                                        \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            ",
                        "                                                            \n"
                        "                        Attack two                          \n"
                        "                        ==========                          \n"
                        "                                                            \n"
                        "      Scrap reuse                                           \n"
                        "      ===========                                           \n"
                        "                                                            \n"
                        "        Cost: 40 battery                                    \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "        Effect:                                             \n"
                        "           Lower the Atk. stat of your enemy by             \n"
                        "            1, than deal lower damage to them.              \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            ","",3);

attacks biohazardAttacks ("                                                            \n"
                          "                        Attack one                          \n"
                          "                        ==========                          \n"
                          "                                                            \n"
                          "      Spore rain                                            \n"
                          "      ==========                                            \n"
                          "                                                            \n"
                          "        Cost: 15 battery, 15 data                           \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "        Effect:                                             \n"
                          "           Deal lower damage to your enemy, but             \n"
                          "           ignore their shield.                             \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            ",
                       "                                                            \n"
                       "                        Attack two                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "      Wood hammer                                           \n"
                       "      ===========                                           \n"
                       "                                                            \n"
                       "        Cost: 40 data                                       \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        Effect:                                             \n"
                       "           Deal higher damage to your enemy and             \n"
                       "           give them poison effect.                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                        Attack three                        \n"
                       "                        ============                        \n"
                       "                                                            \n"
                       "      Flowers burn                                          \n"
                       "      ============                                          \n"
                       "                                                            \n"
                       "        Cost: 40 battery                                    \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        Effect:                                             \n"
                       "           Deal normal damage to your enemy and             \n"
                       "           give them burning effect.                        \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ", 3);

#endif //GAME_ATTACKS_H
