#ifndef GAME_ATTACKS_H
#define GAME_ATTACKS_H

using namespace std;

class attacks {
public:
    string attackOneDescriptionChooseYourCharacter;
    string attackTwoDescriptionChooseYourCharacter;
    string attackThreeDescriptionChooseYourCharacter;



    attacks(string a, string b, string c) {
        attackOneDescriptionChooseYourCharacter = a;
        attackTwoDescriptionChooseYourCharacter = b;
        attackThreeDescriptionChooseYourCharacter = c;
    }
};

attacks infernoAttacks("                                                            \n"
                       "                        Attack one                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "         Shield Melt                                        \n"
                       "         ===========                                        \n"
                       "                                                            \n"
                       "        | Cost: 40 battery                                  \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        | Effect:                                           \n"
                       "            Destroy shield of the enemy, if the enemy       \n"
                       "            doesn't have shield active deal 2 damage        \n"
                       "            to their armour. Than deal normal damage        \n"
                       "            to enemy.                                       \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                        Attack two                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "         Flamethrower Overclock                             \n"
                       "         ======================                             \n"
                       "                                                            \n"
                       "        | Cost: 20 battery, 20 data                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        | Effect:                                           \n"
                       "          Deal a lot of damage to your enemy. Than          \n"
                       "          give them burning effect.                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                       Attack three                         \n"
                       "                       ============                         \n"
                       "                                                            \n"
                       "         Smoke Grenade                                      \n"
                       "         =============                                      \n"
                       "                                                            \n"
                       "        | Cost: 30 battery, 15 data                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        | Effect:                                           \n"
                       "         Give your enemy two effects, burning and poison    \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ");

attacks atlasAttacks ("                                                            \n"
                      "                        Attack one                          \n"
                      "                        ==========                          \n"
                      "                                                            \n"
                      "         Data leach                                         \n"
                      "         ==========                                         \n"
                      "                                                            \n"
                      "        | Cost: 40 battery                                  \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Lower the current stat of data of your enemy     \n"
                      "           by 25% and add this amount to your data stat.    \n"
                      "           After this deal lower damage to your enemy.      \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                        Attack two                          \n"
                      "                        ==========                          \n"
                      "                                                            \n"
                      "          Data Leak                                         \n"
                      "          =========                                         \n"
                      "                                                            \n"
                      "        | Cost: 100% data                                   \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           For every 10 data spent when this activated      \n"
                      "           deal one damage yo your enemy.                   \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                       Attack three                         \n"
                      "                       ============                         \n"
                      "                                                            \n"
                      "         SQL injection                                      \n"
                      "         =============                                      \n"
                      "                                                            \n"
                      "        | Cost: 40 data, 15 battery                         \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal normal amount of damage (your atk stat)     \n"
                      "           to your enemy. Than lower the data stat of       \n"
                      "           your enemy by 20.                                \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ");

attacks hanibalAttacks ("                                                            \n"
                        "                        Attack one                          \n"
                        "                        ==========                          \n"
                        "                                                            \n"
                        "      Big bite                                              \n"
                        "      ========                                              \n"
                        "                                                            \n"
                        "        | Cost: 15 battery                                  \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "        | Effect:                                           \n"
                        "           Ignore armour and deal normal damage             \n"
                        "           to your enemy (lower their hp and                \n"
                        "           not arm).                                        \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            ",
                        "                                                            \n"
                        "                        Attack two                          \n"
                        "                        ==========                          \n"
                        "                                                            \n"
                        "      Scrap reuse                                           \n"
                        "      ===========                                           \n"
                        "                                                            \n"
                        "        | Cost: 40 battery                                  \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "        | Effect:                                           \n"
                        "           Lower the Atk. stat of your enemy by             \n"
                        "            1, than deal lower damage to them.              \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            ",
                        "                                                            \n"
                        "                        Attack three                        \n"
                        "                        ============                        \n"
                        "                                                            \n"
                        "      Spine snap bite                                       \n"
                        "      ===============                                       \n"
                        "                                                            \n"
                        "        | Cost: 40 battery, 40 data                         \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "        | Effect:                                           \n"
                        "           Deal high damage to your enemy they              \n"
                        "           will skip their next turn.                       \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            \n"
                        "                                                            ");

attacks monoIAttacks ("                                                            \n"
                      "                         Attack one                         \n"
                      "                         ==========                         \n"
                      "                                                            \n"
                      "      Shield infection                                      \n"
                      "      ================                                      \n"
                      "                                                            \n"
                      "        | Cost: 40 data                                     \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Destroy shield of your enemy and than            \n"
                      "           create shield that the strength of               \n"
                      "           atk stat of your enemy + 2.                      \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                         Attack two                         \n"
                      "                         =========                          \n"
                      "                                                            \n"
                      "      Meat hook                                             \n"
                      "      =========                                             \n"
                      "                                                            \n"
                      "        | Cost: 40 data, 40 battery                         \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal highest damage possible (high damage        \n"
                      "           of your strongest hero) than deal normal         \n"
                      "           damage and skip your next turn.                  \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                        Attack three                        \n"
                      "                        ============                        \n"
                      "                                                            \n"
                      "      Iron punch                                            \n"
                      "      ==========                                            \n"
                      "                                                            \n"
                      "        | Cost: 15 battery                                  \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal normal damage to your enemy.                \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ");

attacks biohazardAttacks ("                                                            \n"
                          "                        Attack one                          \n"
                          "                        ==========                          \n"
                          "                                                            \n"
                          "      Spore rain                                            \n"
                          "      ==========                                            \n"
                          "                                                            \n"
                          "        | Cost: 15 battery, 15 data                         \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "        | Effect:                                           \n"
                          "           Deal lower damage to your enemy, but             \n"
                          "           ignore their shield.                             \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            \n"
                          "                                                            ",
                       "                                                            \n"
                       "                        Attack two                          \n"
                       "                        ==========                          \n"
                       "                                                            \n"
                       "      Wood hammer                                           \n"
                       "      ===========                                           \n"
                       "                                                            \n"
                       "        | Cost: 40 data                                     \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        | Effect:                                           \n"
                       "           Deal higher damage to your enemy and             \n"
                       "           give them poison effect.                         \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ",
                       "                                                            \n"
                       "                        Attack three                        \n"
                       "                        ============                        \n"
                       "                                                            \n"
                       "      Flowers burn                                          \n"
                       "      ============                                          \n"
                       "                                                            \n"
                       "        | Cost: 40 battery                                  \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "        | Effect:                                           \n"
                       "           Deal normal damage to your enemy and             \n"
                       "           give them burning effect.                        \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            \n"
                       "                                                            ");

attacks zipAttacks ("                                                            \n"
                    "                         Attack one                         \n"
                    "                         ==========                         \n"
                    "                                                            \n"
                    "      Compression                                           \n"
                    "      ===========                                           \n"
                    "                                                            \n"
                    "        | Cost: 15 battery, 15 data                         \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "        | Effect:                                           \n"
                    "           Deal low damage to your enemy and                \n"
                    "           lower their attack stat by one.                  \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            ",
                    "                                                            \n"
                    "                         Attack two                         \n"
                    "                         ==========                         \n"
                    "                                                            \n"
                    "      Zap                                                   \n"
                    "      ===                                                   \n"
                    "                                                            \n"
                    "        | Cost: 15 battery                                  \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "        | Effect:                                           \n"
                    "           Deal higher damage to your enemy.                \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            ",
                    "                                                            \n"
                    "                        Attack three                        \n"
                    "                        ============                        \n"
                    "                                                            \n"
                    "      Decompress shield                                     \n"
                    "      =================                                     \n"
                    "                                                            \n"
                    "        | Cost: 40 battery                                  \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "        | Effect:                                           \n"
                    "           Deal lower damage to your enemy but              \n"
                    "           ignore their shield.                             \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            \n"
                    "                                                            ");

attacks plagyAttacks ("                                                            \n"
                      "                         Attack one                         \n"
                      "                         ==========                         \n"
                      "                                                            \n"
                      "      Release the cyberplague                               \n"
                      "      =======================                               \n"
                      "                                                            \n"
                      "        | Cost: 40 data                                     \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal normal damage to your enemy while           \n"
                      "           ignoring their shield and give them              \n"
                      "           poison effect.                                   \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                         Attack two                         \n"
                      "                         ==========                         \n"
                      "                                                            \n"
                      "      Germs in wound                                        \n"
                      "      ==============                                        \n"
                      "                                                            \n"
                      "        | Cost: 25 battery                                  \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal normal damage to your enemy and             \n"
                      "           give them poison effect.                         \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                        Attack three                        \n"
                      "                        ============                        \n"
                      "                                                            \n"
                      "      Put on the drain worm                                 \n"
                      "      =====================                                 \n"
                      "                                                            \n"
                      "        | Cost: 40 data, 15 battery                         \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Put drain effect on your enemy it can            \n"
                      "           be put away by putting on shield, clearing       \n"
                      "           all effects or by putting on                     \n"
                      "           any other effect.                                \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ");

attacks amperAttacks ("                                                            \n"
                      "                         Attack one                         \n"
                      "                         ==========                         \n"
                      "                                                            \n"
                      "      Trojan bug                                            \n"
                      "      ==========                                            \n"
                      "                                                            \n"
                      "        | Cost: 40 data                                     \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Heal 2 hp and deal 2 dmg to your enemy.          \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                         Attack two                         \n"
                      "                         ==========                         \n"
                      "                                                            \n"
                      "      Virtual punch                                         \n"
                      "      =============                                         \n"
                      "                                                            \n"
                      "        | Cost: 40 data                                     \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal higher damage.                              \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ",
                      "                                                            \n"
                      "                        Attack three                        \n"
                      "                        ============                        \n"
                      "                                                            \n"
                      "      Brute force attack                                    \n"
                      "      ==================                                    \n"
                      "                                                            \n"
                      "        | Cost: 40 battery                                  \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "        | Effect:                                           \n"
                      "           Deal normal damage to your enemy while           \n"
                      "           ignoring their shield.                           \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            \n"
                      "                                                            ");

#endif //GAME_ATTACKS_H
